#! /bin/bash

../myhttpd 0 > /dev/null 2>&1 &
PID=$!
sleep 1
PORT=$(ss -l -p -n | grep $PID | awk '{print $5}' | cut -d ":" -f2)
FILES=$(ls -1 ./http-root-dir/htdocs/)
USERSTRING=$(cat ../auth.txt)
RFILES=$(curl -L -s -u $USERSTRING "127.0.0.1:$PORT/dir1/" | grep "href" | grep -v -E "C=N|C=M|C=S")
for FILE in $RFILES; do
  ls -1 ./http-root-dir/htdocs/dir1/ | grep $(python htmlsearch.py '$FILE')
  if [[ $? != 0 ]]; then
    printf "\033[0;31m$(basename "$0")  Failed.\033[0m\n"
    rm -rf ./tmp/*
    kill -15 $PID
  fi
done
printf "\033[0;32m$(basename "$0")  Passed.\033[0m\n"
rm -f ./tmp/*
kill -15 $PID
